### ISSUE TITLE
Problem when printing string with 2 control codes

### ISSUE THREAD

**Issue by viteisele** [nietoperz809/C64Screen#3]
Testprogramm:
10 print chr$(151)+"1"+chr$(155)+"2"
20 print chr$(151)+"1";chr$(155)+"2"

The output should be identical for both lines (different colors for 1 and 2), but with C64Screen only line 20 prints a correct result.

**Comment by nietoperz809** [comment]
now works as expected.
plus updated jar file
testproggy is in "ctrlcode.bas"

**Comment by viteisele** [comment]
It works also on my PC.  Thank you :-)
